repos:
- repo: local
  hooks:
  - id: pytest
    name: pytest
    stages: [commit]
    language: system
    entry: pytest
    types: [python]

  - id: pytest-cov
    name: pytest
    stages: [push]
    language: system
    entry: pytest --cov
    types: [python]
    pass_filenames: false

  # - id: black
  #   name: black
  #   stages: [commit]
  #   language: system
  #   entry: python3 black
  #   types: [python]

  # - id: mypy
  #   name: mypy
  #   stages: [commit]
  #   language: system
  #   entry: python mypy
  #   types: [python]
  #   pass_filenames: false

